// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmFaCQsiamZ83XilvEHBI52J5zOAFGFA',
    appId: '1:741796399220:web:032f24fc15291333622921',
    messagingSenderId: '741796399220',
    projectId: 'nutriauth',
    authDomain: 'nutriauth.firebaseapp.com',
    storageBucket: 'nutriauth.appspot.com',
    measurementId: 'G-VLDP42Y0MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SxL9MnsMLNoeQe_vmkxQhpRVSd_s6MQ',
    appId: '1:741796399220:android:a9fc7fe3986aef5b622921',
    messagingSenderId: '741796399220',
    projectId: 'nutriauth',
    storageBucket: 'nutriauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsOeMpkCqo4tlFq53g6fAI_JiSrCtw8Q',
    appId: '1:741796399220:ios:e6630374c4738714622921',
    messagingSenderId: '741796399220',
    projectId: 'nutriauth',
    storageBucket: 'nutriauth.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUmFaCQsiamZ83XilvEHBI52J5zOAFGFA',
    appId: '1:741796399220:web:3832b79b941d6052622921',
    messagingSenderId: '741796399220',
    projectId: 'nutriauth',
    authDomain: 'nutriauth.firebaseapp.com',
    storageBucket: 'nutriauth.appspot.com',
    measurementId: 'G-JK1XY65Y8P',
  );
}
